language: python
python: '3.7'
install:
  - pip install -e .[tests]
  - pip install sphinx sphinx_rtd_theme
script:
  - black --check deepsphere/ scripts/
  - python -m unittest discover -v
  - isort -rc --check-only deepsphere/ scripts/
  - pylint-fail-under --rcfile=setup.cfg --fail_under 9.5 deepsphere/ scripts/
  - cd docs && make html

branches:
  only:
  - readthedocs

deploy:
  provider: pypi
  user: __token__
  password:
    secure: KSwXM9g+ZDE1hHFghbfU2dt3mewwo5WeoKqi6BnO6WVGSBECemTj6H/+wrxUrU9oULT8L2hTEr6ZiiFvRG//awOFEDqMZgCANSKtl6P+F8rXRfsYhkx30eNbhI8xfdsvYFodLXLbX5vjjNk0uBs4FlS+s5TVE91RTkaHFtowSEnhKGuDhKMaBqK9j7ZxL2wQoyfgIeJSQg8+d663kXLAhzVrCsV0Q1qAxX5f9C/iQv3vscDCE4mTo7DChxVWbNyzZ/bhBfo8DzshsT45DvO+wRhafPzXvyb3z/w6sit360WEYxFftlUm44/sVu0eflzUPfPFIT1qrlL2AG+ClZMuPjUzgZ63YwAqfJAxjaq7RVqjSlNrpZNlg7W+P3fTFMnNvVrfW0eZzxXIfFBJjwEOJD8JTJUHPPiZCMHR0Rz0ovhp5o1Tf2lcPFwiTVKtLmSUVNo5HAsMfyTCL09tW/VP4vZMMzsYTgY3EPBU9T2NWE/qa69/wo3Qp8YuzEvX4qsZ9iIXHkomQEAd469ZUmaMaMTXzvnDeDJ/szB5xiI56+rVkvc/G7lR8mDDdiJA+ml6y/pqW3PtsOMHEsl/oJ/rnWvl95hamJcUKubuQxCmTIWqmsC8nKmng3Z9jisBxCmu+IfQ0Rdm5KicssItbOkvDDK2CNSJYHM2gb+SRZ2DgNM=
