language: python

python:
  - '3.7'

install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt


script:
  - python -m unittest discover -v
  - isort -rc --check-only deepsphere/ scripts/
  - pylint-fail-under --rcfile=setuf.cfg --fail_under 9.5 deepsphere/ scripts/
  - black --check deepsphere/ scripts/
  - cd docs/
  - make html
  mv build/html/ ../public/

deploy:
  provider: pypi
  user: __token__
  password:
    secure: Duviwxs8e7tul9Af5GcPqVJ65ED/PB4RhpED5chmsqwAnXOSl1met2txoIaDkZ0cZ3WbHGnYUtMbIothaOYOWys3g+N1pg9pDe5h9aDE7fStS4WnBBN4N7k4TtOA770yy6o8og3oDVKTE/iJkM9ibiQ9WafBxSWewFYOvnvJGiXCfATHfG3lqwt26blVcGLsssWHfiqWtBUfwsiHWPPTMtyyIu6KzEcOHnZNdzNoogsGcawmtqZPqcx2+1YhhbMe1htYDHVFzfYNezoBQ41chw+bCRDXOujlqs1ODlqS3hwCOnPn59Fhu2hT7l/XnAr8k6I08O977PMOgwklUTNkQCef5dE4qrHK6vVNosjjw4G8bXfLelZqOiYzhn8TUQ1MYX2wE7hgRG7EiBU/klW7Vujp7y7SR7b05hwfJ8SDLSVfGQ2wptXJ8Y/m8wHjI0XwLUq7CKAYEvFF2IJrGhAORTEyZOyn7Sofb60lP0IKrp+bPvaE5i0IIl6gximGkjpBB84wF7DN1k2DR9MOri/FltPBMs4PSNQ5qh97qtBEbqhbpuSAIxOiV3Yq5gSUKfbkO4MIgFi2IbZkADQvb/Fkre01Y4MOfZzbARio3IwnFVLXudbsTXLxpeApU2GWek8rf8EzJ/9W+57FHyo2EomOCmziaUBAqpkX7APnJzvhSqE=
